services:
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - ./_pgdata:/var/lib/postgresql/data
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    volumes:
      - ./.minio:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio-secret
      MINIO_REGION_NAME: eu-west-3
    command: server --console-address :9001 /data
    restart: unless-stopped

  createbuckets:
    image: minio/mc:RELEASE.2023-04-12T02-21-51Z
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 3;
        mc config host add s3 http://minio:9000 minio minio-secret;
        mc mb -p s3/timesinkpresents;
        mc policy set public s3/timesinkpresents;
        exit 0;
      "