services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    volumes:
      - .docker/minio/data:/data
    ports:
      - 9000:9000
      - 9001:9001
    command: server --console-address :9001 /data

  minio_autosetup:
    image: minio/mc:RELEASE.2024-11-17T19-35-25Z
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 3;
        mc config host add minio http://minio:9000 minioadmin minioadmin;
        mc mb -p minio/timesink.prod/public;
        mc anonymous set public minio/timesink.prod/public;
        exit 0;
      "
