name: Deploy Staging to Fly.io

on:
  push:
    branches:
      - staging  # Deploys when pushing to 'staging' branch

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15'  # Update to your version
          otp-version: '26'       # Update to your version

      - name: Install Node.js and Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Use latest stable Node.js
      - run: |
          cd assets
          npm ci  # Installs dependencies from package-lock.json for reproducibility

      - name: Install Fly.io CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Authenticate with Fly.io
        run: fly auth whoami
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Deploy to Fly.io
        run: fly deploy --app timesink-staging --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
